# Description:
#   - Release Nu Pkgs
# REF:
#   - https://github.com/marketplace/actions/checkout
#   - https://github.com/chawyehsu/moonbit-binaries/releases

name: Publish Nu Pkgs
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
      - '!*nightly*'  # Don't trigger release for nightly tags

    paths-ignore:
      - '**.md'

jobs:
  publish-pkgs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    name: Build Nu Pkgs@${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3

      - name: Install nfpm & Gemfury CLI
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/cli/ * *" | sudo tee /etc/apt/sources.list.d/fury-cli.list
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm fury-cli
          nfpm --version
          fury --version

      - name: Build and Publish Nu Pkgs
        shell: nu {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          NFPM_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          use ${{ github.workspace }}/nu/release.nu *
          version | print
          let version = open meta.json | get version
          echo $env.SIGNING_KEY o> key.gpg
          # $env | print
          let arch = match $env.RUNNER_ARCH {
              'X64' => 'amd64',
              'ARM64' => 'arm64',
              _ => 'amd64'
            }
          fetch release $arch $version
          publish pkg $arch --create-release
          rm key.gpg

  publish-others:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    name: Build Nu Pkgs for Other ARCHs
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3

      - name: Install nfpm & Gemfury CLI
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/cli/ * *" | sudo tee /etc/apt/sources.list.d/fury-cli.list
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm fury-cli
          nfpm --version
          fury --version

      - name: Build and Publish Nu Pkgs
        shell: nu {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          NFPM_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          use ${{ github.workspace }}/nu/release.nu *
          version | print
          let version = open meta.json | get version
          echo $env.SIGNING_KEY o> key.gpg
          fetch release riscv64 $version
          publish pkg riscv64 --create-release
          fetch release loongarch64 $version
          publish pkg loongarch64 --create-release
          rm key.gpg

  sha256sum:
    needs: [publish-pkgs , publish-others]
    name: Create Sha256sum
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Nushell
      uses: hustcer/setup-nu@v3
    - name: Calc Tag and Upload Source Archive
      id: tag
      shell: nu {0}
      run: |
        let meta = open ${{ github.workspace }}/meta.json
        let tag = $'($meta.version)-($meta.revision)'
        $'tag_name=($tag)(char nl)' o>> $env.GITHUB_OUTPUT
        http get https://api.github.com/repos/nushell/nushell/tarball/($meta.version)
          | save -rpf $'nushell-($tag)-source.tar.gz'
        gh release upload $tag -R ${{ github.repository }} --clobber nushell-($tag)-source.tar.gz
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download Release Archives
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >-
        gh release download ${{ steps.tag.outputs.tag_name }}
        --repo ${{ github.repository }}
        --pattern '*'
        --dir release
    - name: Create Checksums
      run: cd release && shasum -a 256 * > ../SHA256SUMS
    - name: Publish Checksums
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: SHA256SUMS
        tag_name: ${{ steps.tag.outputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

